### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by tomplant0** [WillyXevo/Igrabber#1]
Hi there, 

I was trying to test your script but I get an error with every photo, video, igtv, ect. Do you know how I can fix this? This is the code I get:

INFO
Array
(
    [url] => https://www.instagram.com/p/CC1fkqagP56/?utm_source=ig_web_copy_link
    [content_type] => text/html; charset=utf-8
    [http_code] => 302
    [header_size] => 2024
    [request_size] => 224
    [filetime] => -1
    [ssl_verify_result] => 0
    [redirect_count] => 0
    [total_time] => 0.21415
    [namelookup_time] => 0.004204
    [connect_time] => 0.03295
    [pretransfer_time] => 0.065708
    [size_upload] => 0
    [size_download] => 0
    [speed_download] => 0
    [speed_upload] => 0
    [download_content_length] => 0
    [upload_content_length] => -1
    [starttransfer_time] => 0.214094
    [redirect_time] => 0
    [redirect_url] => https://www.instagram.com/accounts/login/?next=/p/CC1fkqagP56/%3Futm_source%3Dig_web_copy_link
    [primary_ip] => 2a03:2880:f245:e0:face:b00c:0:4420
    [certinfo] => Array
        (
        )

    [primary_port] => 443
    [local_ip] => 2a01:4f9:c010:833e::1
    [local_port] => 47528
    [http_version] => 3
    [protocol] => 2
    [ssl_verifyresult] => 0
    [scheme] => HTTPS
    [appconnect_time_us] => 65473
    [connect_time_us] => 32950
    [namelookup_time_us] => 4204
    [pretransfer_time_us] => 65708
    [redirect_time_us] => 0
    [starttransfer_time_us] => 214094
    [total_time_us] => 214150
)
ERROR
Array
(
)
Link tidak valid

**Comment by WillyXevo** [comment]
Fixed, changed "scraping with php" to using API.
so this repository is only as UI and for the process using the API from my other repository, namely [Igrabber_api](https://github.com/WillyXevo/Igrabber_api)
